# Font configuration for Alacritty
# Using JetBrains Mono Nerd Font for compatibility with terminal icons

[font]
# Normal (roman) font face
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# Bold font face
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }

# Italic font face
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

# Bold italic font face
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# Font size
size = 12.0

# Offset is the extra space around each character
offset = { x = 0, y = 0 }

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }

# Use built-in font for box drawing characters
builtin_box_drawing = true
