# Window configuration
[window]
opacity = 0.95
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
dynamic_padding = true
title = "Alacritty"
dynamic_title = true
decorations = "Full"
