# Configuration Starship - Version simplifiée
# Fichier: ~/.config/starship.toml

# Format général du prompt - version minimaliste
format = "$directory$git_branch$character"

# Désactiver la ligne vide à la fin du prompt
add_newline = false

# Caractère du prompt
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

# Affichage du répertoire courant
[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = true

# Affichage de la branche Git (simplifié)
[git_branch]
format = "[git:$branch]($style) "
symbol = ""
style = "purple"

# Désactiver les modules non essentiels
[username]
disabled = true

[hostname]
disabled = true

[git_status]
disabled = true

[cmd_duration]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[docker_context]
disabled = true
