# Configuration Starship avec un thème inspiré de Catppuccin Macchiato
# Pour plus d'options: https://starship.rs/config/

# Configuration générale
add_newline = true
command_timeout = 1000

# Format du prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

# Caractère du prompt
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

# Répertoire courant
[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"
format = "[$path]($style) "

# Branche Git
[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"

# État Git
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold yellow"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

# Python
[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
style = "bold cyan"
detect_extensions = ["py"]
python_binary = ["python", "python3", "python2"]

# Node.js
[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold green"
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]

# Rust
[rust]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold red"
detect_extensions = ["rs"]

# Go
[golang]
format = "[$symbol($version )]($style)"
symbol = " "
style = "bold cyan"
detect_extensions = ["go"]

# Durée de la commande
[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "yellow"

# Nom d'utilisateur
[username]
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = false

# Nom d'hôte
[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold green"

# Batterie
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"
